name: Up to Date

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn

      - name: Generate Cheat Sheet
        run: yarn generate

      - name: Deploy New Cheat Sheet
        run: |
          git diff --name-only --exit-code && exit 0
          git add README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "docs(readme): update emoji-cheat-sheet"
          git push -q "https://${{ secrets.GITHUB_TOKEN }}@github.com/ikatyang/emoji-cheat-sheet.git"
